/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package REST_SM;

import spark.Spark;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Spark.get("/users/0/welcome", (req, res) -> {return "Hallo Ueli";});
        Spark.get("/users/1/welcome", (req, res) -> {return "Hallo Sue";});
        System.out.println(new App().getGreeting());
    }
}
